// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	datatype "github.com/leosimoesp/civi-backend-exercise/internal/app/datatype"
	mock "github.com/stretchr/testify/mock"
)

// PointRepo is an autogenerated mock type for the PointRepo type
type PointRepo struct {
	mock.Mock
}

// GetAllPoints provides a mock function with given fields:
func (_m *PointRepo) GetAllPoints() ([]datatype.Point, error) {
	ret := _m.Called()

	var r0 []datatype.Point
	if rf, ok := ret.Get(0).(func() []datatype.Point); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]datatype.Point)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
